__liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

mark_menu:
    resource: "@MarkMenuBundle/Controller/"
    type:     annotation
#    prefix:   /

mark_general:
    resource: "@MarkGeneralBundle/Controller/"
    type:     annotation
    prefix:   /

mark_login:
    resource: "@MarkLoginBundle/Controller/"
    type:     annotation
    prefix:   /

logout:
    path: /logout