parameters:

services:
    security.authentication_utils:
        class: Symfony\Component\Security\Http\Authentication\AuthenticationUtils
        arguments: ["@request_stack"]

    user.loggeduser_utils:
        class: Mark\LoginBundle\Controller\UserUtilsController
        arguments: ["@security.token_storage"]