parameters:

services:

    app.locale_listener:
        class: Mark\LoginBundle\EventListener\LocaleListener
        arguments: ['%kernel.default_locale%']
        tags:
            - { name: kernel.event_subscriber }

    app.user_locale_listener:
        class: Mark\LoginBundle\EventListener\UserLocaleListener
        arguments: [@session]
        tags:
        - { name: kernel.event_listener, event: security.interactive_login, method: onInteractiveLogin }